updated fastlane for ios

diff --git a/.github/workflows/ios_workflow.yml b/.github/workflows/ios_workflow.yml
--- a/.github/workflows/ios_workflow.yml
+++ b/.github/workflows/ios_workflow.yml
@@ -21,13 +21,6 @@ jobs:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
-      # Set up Ruby for Fastlane
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 3.1.0
-          bundler-cache: true
-
       - name: Set Xcode Command Line Tools
         run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
 
@@ -83,13 +76,24 @@ jobs:
         env:
           GOOGLE_SERVICE_INFO: ${{ secrets.GOOGLE_INFO_PLIST }}
 
+      - name: Install Fastlane
+        working-directory: ios
+        run: bundle install
+
       - name: Increment Version & Build Number
         working-directory: ios
         run: bundle exec fastlane fetch_and_increment_build_number
 
       - name: Fetch updated build number
         working-directory: ios
-        run: echo "BUILD_NUMBER=$(agvtool what-version -terse)" >> $GITHUB_ENV
+        run: |
+          if [ ! -f build_number.txt ]; then
+            echo "❌ build_number.txt not found!"
+            exit 1
+          fi
+          BUILD_NUMBER=$(cat build_number.txt | tr -d '\n')
+          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
+          echo "✅ Updated Build Number: $BUILD_NUMBER"
 
       - name: Build IPA for Distribution
         run: |
